title: Marco Martinez Portfolio 
description: >-
         This is my portfolio showcasing my projects and skills.
baseurl: "" # leave empty since this is your user page
url: "https://mm1279544.github.io" # replace YOURUSERNAME with your GitHub username
theme: jekyll-theme-architect # replace minima with your chosen theme from the list
